
# url: "https://cepdnaclk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "ESCAL" # the name of your site, e.g. ACME Corp.

# include: ['_pages']

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap

# Google Analytics Tracking (optional)
ga_tracking:
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

permalink: pretty
exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
    "graphic_templates",
    "*.py",
    "*.sh",
    "*.yml"
  ]

kramdown:
  syntax_highlighter_opts:
    block:
    line_numbers: false
